name: NewTests

on:
  schedule:
    - cron: '07 20 * * *'
    - cron: '08 20 * * *'
    - cron: '09 20 * * *'
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]
  workflow_dispatch:
    inputs:
      browser:
        description: 'Choose a browser'
        required: true
        default: 'chrome'
        type: choice
        options:
          - chrome
          - edge
          - safari
          - firefox
      suite:
        description: 'Choose a test suite'
        required: true
        default: 'smoke'
        type: choice
        options:
          - smoke
          - regression
          - api

jobs:
  tests:
    runs-on: windows-latest
    strategy:
      matrix:
        include:
          - suite: api
            browser: chrome
       
          - suite: smoke
            browser: edge
          
          - suite: regression
            browser: ${{ github.event.inputs.browser || 'chrome' }}
          
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'corretto'
        cache: maven
        
    - name: Run tests
      run: mvn -B clean test -Dbrowser=${{ matrix.browser }} -Dsuite=${{ matrix.suite }}
      
    - name: Generate Allure report
      if: always()
      run: mvn allure:report
    - name: Upload Allure Report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: allure-report
        path: target/allure-results
