name: NewTests

on:
  schedule:
    - cron: '30 22 * * *'
    - cron: '30 23 * * *'
    - cron: '30 20 * * *'
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]
  workflow_dispatch:
    inputs:
      browser:
        description: 'Choose a browser'
        required: true
        default: 'chrome'
        type: choice
        options:
          - chrome
          - edge
          - safari
          - firefox
      suite:
        description: 'Choose a test suite'
        required: true
        default: 'smoke'
        type: choice
        options:
          - smoke
          - regression
          - api

jobs:
  api_suite:
    runs-on: windows-latest
    if: github.event.schedule == '30 22 * * *' 
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'corretto'
          cache: maven

      - name: Run API tests on Chrome
        run: mvn -B clean test -Dsuite=api -Dbrowser=edge

      - name: Generate Allure report
        if: always()
        run: mvn allure:report

      - name: Upload Allure Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: target/allure-results

  smoke_suite:
    runs-on: windows-latest
    if: github.event.schedule == '30 23 * * *' || github.event.inputs.suite == 'smoke'
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'corretto'
          cache: maven

      - name: Run Smoke tests on Edge
        run: mvn -B clean test -Dsuite=smoke -Dbrowser=chrome

      - name: Generate Allure report
        if: always()
        run: mvn allure:report

      - name: Upload Allure Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: target/allure-results

  regression_suite:
    runs-on: windows-latest
    if: github.event.schedule == '30 20 * * *' || github.event.inputs.suite == 'regression'
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'corretto'
          cache: maven

      - name: Run Regression tests on default browser
        run: mvn -B clean test -Dbrowser=${{ github.event.inputs.browser || 'chrome' }} -Dsuite=regression

      - name: Generate Allure report
        if: always()
        run: mvn allure:report

      - name: Upload Allure Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-report-${{ github.run_id }}
          path: target/allure-results
     
